//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCourseDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPATCHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISPATCHER()
        {
            this.REPAIR_ORDER = new HashSet<REPAIR_ORDER>();
            this.WORK_ORDER = new HashSet<WORK_ORDER>();
        }
    
        public string ID { get; set; }
        public string DISPATCH_START { get; set; }
        public string DISPATCH_STOP { get; set; }
        public string INSERT_BY { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime INSERT_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIR_ORDER> REPAIR_ORDER { get; set; }
        public virtual STAFF STAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_ORDER> WORK_ORDER { get; set; }
    }
}
