//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCourseDesign.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FEMSContext : DbContext
    {
        public FEMSContext()
            : base("name=FEMSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCESSORY> ACCESSORY { get; set; }
        public virtual DbSet<ACCESSORY_STORED> ACCESSORY_STORED { get; set; }
        public virtual DbSet<DISPATCHER> DISPATCHER { get; set; }
        public virtual DbSet<EQ_IN_USE> EQ_IN_USE { get; set; }
        public virtual DbSet<EQ_STORED> EQ_STORED { get; set; }
        public virtual DbSet<EQ_TYPE> EQ_TYPE { get; set; }
        public virtual DbSet<EQ_TYPE_ACCESSORY> EQ_TYPE_ACCESSORY { get; set; }
        public virtual DbSet<FACTORY> FACTORY { get; set; }
        public virtual DbSet<PATROL> PATROL { get; set; }
        public virtual DbSet<PATROL_LOG> PATROL_LOG { get; set; }
        public virtual DbSet<PATROL_REGION> PATROL_REGION { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<REPAIR_ORDER> REPAIR_ORDER { get; set; }
        public virtual DbSet<REPAIRER> REPAIRER { get; set; }
        public virtual DbSet<REPAIRER_REGION> REPAIRER_REGION { get; set; }
        public virtual DbSet<WAREHOUSE> WAREHOUSE { get; set; }
        public virtual DbSet<WORK_ORDER> WORK_ORDER { get; set; }
        public virtual DbSet<STAFF> STAFF { get; set; }
    }
}
